const bcrypt = require('bcryptjs');

// Pre-hashed "password123"
const DEFAULT_HASH = '$2a$10$3euPcmqf4Uiqr0BvK1tMduf29s5h9d/7iU5p07/4a2yV3cZt82gqy';

const initialUsers = [
  {
    id: 1,
    name: 'Rahul Sharma',
    email: 'demo@eventhub.com',
    password_hash: DEFAULT_HASH,
    role: 'CUSTOMER',
    phone: '+91 98765 43210',
    city: 'Patna',
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    name: 'Sharma Caterers Admin',
    email: 'vendor@eventhub.com',
    password_hash: DEFAULT_HASH,
    role: 'VENDOR',
    phone: '+91 98123 45678',
    city: 'Patna',
    created_at: new Date().toISOString()
  },
  {
    id: 3,
    name: 'Rajesh Verma (Royal Palace)',
    email: 'royalpalace@eventhub.com',
    password_hash: DEFAULT_HASH,
    role: 'VENDOR',
    phone: '+91 94310 11223',
    city: 'Patna',
    created_at: new Date().toISOString()
  },
  {
    id: 4,
    name: 'Priya Singh',
    email: 'priya@example.com',
    password_hash: DEFAULT_HASH,
    role: 'CUSTOMER',
    phone: '+91 91234 56789',
    city: 'Gaya',
    created_at: new Date().toISOString()
  }
];

const initialVendors = [
  {
    id: 1,
    user_id: 3,
    business_name: 'The Royal Heritage Banquet',
    category: 'Venue',
    city: 'Patna',
    address: 'Bailey Road, Near Saguna More, Patna',
    starting_price: 70000.00,
    price_unit: 'per day',
    rating: 4.8,
    review_count: 42,
    is_verified: 1,
    description: 'Spacious premium banquet hall with modern lighting, bridal suite, air conditioning, and full power backup. Ideal for grand weddings and receptions.',
    facilities: 'Full AC, Parking (80 cars), 24/7 Power Backup, Bridal Room, In-house Sound System, Elevator',
    supported_events: 'Wedding, Reception, Anniversary, Corporate',
    max_capacity: 350,
    halls_info: 'Grand Ball Hall: 250 guests, Open Lawn: 150 guests',
    rooms_count: 10,
    image_gradient: 'linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    user_id: null,
    business_name: 'Gaya Grand Utsav Resort',
    category: 'Venue',
    city: 'Gaya',
    address: 'Bodhgaya Road, Kendui, Gaya',
    starting_price: 60000.00,
    price_unit: 'per day',
    rating: 4.6,
    review_count: 28,
    is_verified: 1,
    description: 'Serene destination venue with large green lawns and banquet halls close to Bodhgaya. Perfect for destination weddings & family celebrations.',
    facilities: 'AC Banquet, Lush Lawn, Valet Parking (60 cars), Swimming Pool, Stage Setup',
    supported_events: 'Wedding, Engagement, Birthday, Sangeet',
    max_capacity: 400,
    halls_info: 'Main Heritage Hall: 220 guests, Garden Area: 200 guests',
    rooms_count: 14,
    image_gradient: 'linear-gradient(135deg, #065f46 0%, #10b981 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 3,
    user_id: null,
    business_name: 'Muzaffarpur Crystal Palace',
    category: 'Venue',
    city: 'Muzaffarpur',
    address: 'Club Road, Mithanpura, Muzaffarpur',
    starting_price: 55000.00,
    price_unit: 'per day',
    rating: 4.5,
    review_count: 19,
    is_verified: 1,
    description: 'Budget-friendly elegant venue in the heart of Muzaffarpur with sound systems, changing rooms, and warm hospitality.',
    facilities: 'AC Hall, Parking (40 cars), In-house Lighting, Generator Backup',
    supported_events: 'Wedding, Reception, Birthday, Conference',
    max_capacity: 250,
    halls_info: 'Crystal Hall: 200 guests, Mini Hall: 50 guests',
    rooms_count: 6,
    image_gradient: 'linear-gradient(135deg, #831843 0%, #ec4899 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 4,
    user_id: null,
    business_name: 'Bhagalpur Silk City Manor',
    category: 'Venue',
    city: 'Bhagalpur',
    address: 'Zero Mile, Barari, Bhagalpur',
    starting_price: 65000.00,
    price_unit: 'per day',
    rating: 4.7,
    review_count: 23,
    is_verified: 1,
    description: 'Lush open lawn and banquet hall combo tailored for traditional Bihari weddings with dedicated mandap area.',
    facilities: 'Open Green Lawn, AC Dining Hall, 8 AC Rooms, Mandap Canopy, Parking (50 cars)',
    supported_events: 'Wedding, Sangeet, Tilak, Reception',
    max_capacity: 500,
    halls_info: 'Imperial Lawn: 350 guests, Banquet: 150 guests',
    rooms_count: 8,
    image_gradient: 'linear-gradient(135deg, #7c2d12 0%, #f97316 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 5,
    user_id: 2,
    business_name: 'Sharma Caterers & Sweets',
    category: 'Catering',
    city: 'Patna',
    address: 'Boring Road, Patna',
    starting_price: 90000.00,
    price_unit: 'for 250 guests',
    rating: 4.9,
    review_count: 64,
    is_verified: 1,
    description: 'Specialized in authentic North Indian, Maithili, and Continental delicacies. Known for live counters and hygienic kitchen practices.',
    facilities: 'Live Chaat Counter, Welcome Drinks, South Indian, North Indian, Traditional Desserts, Uniformed Staff',
    supported_events: 'Wedding, Birthday, Corporate, Reception',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #b45309 0%, #f59e0b 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 6,
    user_id: null,
    business_name: 'Annapurna Gourmet Catering',
    category: 'Catering',
    city: 'Gaya',
    address: 'Station Road, Gaya',
    starting_price: 75000.00,
    price_unit: 'for 200 guests',
    rating: 4.6,
    review_count: 31,
    is_verified: 1,
    description: 'Traditional Pure Veg gourmet catering providing custom menus, lavish dessert buffets, and live tandoor stations.',
    facilities: 'Pure Vegetarian, Live Tandoor, Mocktail Bar, Hygienic Stalls, Traditional Thali Service',
    supported_events: 'Wedding, Tilak, Anniversary, Mundan',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #15803d 0%, #84cc16 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 7,
    user_id: null,
    business_name: 'Mithila Feast Caterers',
    category: 'Catering',
    city: 'Muzaffarpur',
    address: 'Aghoria Bazar, Muzaffarpur',
    starting_price: 80000.00,
    price_unit: 'for 220 guests',
    rating: 4.7,
    review_count: 29,
    is_verified: 1,
    description: 'Authentic local flavours, famous for Litti Chokha live stall, Kheer, Paneer lababdar and diverse wedding spreads.',
    facilities: 'Live Regional Counters, Chinese & Continental, Cutlery & Waitstaff, Mineral Water Dispensers',
    supported_events: 'Wedding, Reception, Birthday',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #9d174d 0%, #f43f5e 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 8,
    user_id: null,
    business_name: 'Utsav Mandap & Floral Decor',
    category: 'Decoration',
    city: 'Patna',
    address: 'Kankarbagh Main Road, Patna',
    starting_price: 40000.00,
    price_unit: 'per event',
    rating: 4.8,
    review_count: 51,
    is_verified: 1,
    description: 'Creative floral backdrops, grand entry gates, fairy-light canopies, and custom theme stages.',
    facilities: 'Fresh Flowers, LED Theme Lighting, Photo Booth Backdrop, Red Carpet Entry, Varmala Stage',
    supported_events: 'Wedding, Reception, Engagement, Birthday',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #6d28d9 0%, #a855f7 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 9,
    user_id: null,
    business_name: 'Shree Radhey Event Art & Decor',
    category: 'Decoration',
    city: 'Gaya',
    address: 'Rampur, Gaya',
    starting_price: 32000.00,
    price_unit: 'per event',
    rating: 4.5,
    review_count: 22,
    is_verified: 1,
    description: 'Contemporary and eco-friendly wedding decor setups including pastel drapes, selfie corners, and marigold themes.',
    facilities: 'Eco-friendly Props, Stage Lighting, Haldi/Mehendi Setups, Drapes & Carpets',
    supported_events: 'Haldi, Mehendi, Wedding, Birthday',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #4338ca 0%, #6366f1 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 10,
    user_id: null,
    business_name: 'Magadh Royal Decorators',
    category: 'Decoration',
    city: 'Begusarai',
    address: 'Har-Har Mahadev Chowk, Begusarai',
    starting_price: 35000.00,
    price_unit: 'per event',
    rating: 4.6,
    review_count: 17,
    is_verified: 1,
    description: 'Grand entry gates, hydraulic varmala stages, laser lighting, and customized bridal seating designs.',
    facilities: 'Hydraulic Stage, Cold Pyro, Flower Rain, Floral Arches, Ceiling Drapes',
    supported_events: 'Wedding, Sangeet, Tilak',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #0e7490 0%, #06b6d4 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 11,
    user_id: null,
    business_name: 'Lens & Moments Wedding Studio',
    category: 'Photography',
    city: 'Patna',
    address: 'Fraser Road, Dak Bungalow, Patna',
    starting_price: 35000.00,
    price_unit: '2-day coverage',
    rating: 4.9,
    review_count: 58,
    is_verified: 1,
    description: 'Cinematic wedding films, candid moments capture, drone coverage, and premium photobook albums.',
    facilities: '2 Traditional + 1 Candid Photographer, 4K Cinematic Teaser, Drone Shoot, 40-page Matte Album',
    supported_events: 'Wedding, Pre-wedding, Reception, Birthday',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #374151 0%, #1f2937 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 12,
    user_id: null,
    business_name: 'Aura Cine Films & Photography',
    category: 'Photography',
    city: 'Muzaffarpur',
    address: 'Zero Mile, Muzaffarpur',
    starting_price: 30000.00,
    price_unit: '2-day coverage',
    rating: 4.7,
    review_count: 34,
    is_verified: 1,
    description: 'High-definition candid photography, Instagram reel cuts, live LED wall broadcasting, and same-day teaser delivery.',
    facilities: 'Drone Coverage, Live Youtube/LED Broadcast, Candid Portraits, Photobook, Short Video Reels',
    supported_events: 'Wedding, Ring Ceremony, Birthday',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #1e293b 0%, #475569 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 13,
    user_id: null,
    business_name: 'DJ Akhil Beats & Sound System',
    category: 'DJ',
    city: 'Patna',
    address: 'Anisabad, Patna',
    starting_price: 25000.00,
    price_unit: '4-hour session',
    rating: 4.8,
    review_count: 47,
    is_verified: 1,
    description: 'JBL Line-array sound system, moving head lights, smoke machines, and energetic club/Bhojpuri/Bollywood fusion mixes.',
    facilities: 'JBL 4-Bass 4-Top, Moving Heads, Smoke Machine, Wireless Mics, Bollywood & Punjabi DJ set',
    supported_events: 'Sangeet, Baraat, Birthday, Reception',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #be123c 0%, #fb7185 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 14,
    user_id: null,
    business_name: 'BassBlaster Pro DJ & Lighting',
    category: 'DJ',
    city: 'Gaya',
    address: 'Civil Lines, Gaya',
    starting_price: 20000.00,
    price_unit: '4-hour session',
    rating: 4.6,
    review_count: 25,
    is_verified: 1,
    description: 'High-power sound system, truss lighting, party laser effects, and custom Baraat mobile sound setups.',
    facilities: 'Heavy Bass Subs, Truss Setup, Strobe Lights, Custom Playlist, Backup Sound Unit',
    supported_events: 'Baraat, Birthday, Sangeet',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #7e22ce 0%, #c084fc 100%)',
    created_at: new Date().toISOString()
  },
  {
    id: 15,
    user_id: null,
    business_name: 'Glamour by Shweta - Bridal Studio',
    category: 'Makeup',
    city: 'Patna',
    address: 'Boring Canal Road, Patna',
    starting_price: 15000.00,
    price_unit: 'per look',
    rating: 4.9,
    review_count: 39,
    is_verified: 1,
    description: 'HD Airbrush bridal makeup, hair styling, saree draping, and pre-bridal skin care sessions with high-end international cosmetics.',
    facilities: 'Airbrush Makeup, MAC & Huda Beauty Products, Saree/Lehenga Draping, Hair Accessories, False Lashes',
    supported_events: 'Bridal, Reception, Engagement, Party',
    max_capacity: null,
    halls_info: null,
    rooms_count: 0,
    image_gradient: 'linear-gradient(135deg, #db2777 0%, #f472b6 100%)',
    created_at: new Date().toISOString()
  }
];

const initialReviews = [
  {
    id: 1,
    vendor_id: 1,
    user_id: 1,
    reviewer_name: 'Amitabh Roy',
    rating: 5,
    comment: 'The Royal Heritage banquet hall made our wedding seamless! The AC was very effective, ample parking for our 250 guests, and the staff coordinated smoothly.',
    event_type: 'Wedding',
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    vendor_id: 1,
    user_id: null,
    reviewer_name: 'Sunita Kumari',
    rating: 5,
    comment: 'Clean rooms, spacious banquet hall, and great stage setup. True value for money in Patna.',
    event_type: 'Reception',
    created_at: new Date().toISOString()
  },
  {
    id: 3,
    vendor_id: 5,
    user_id: 1,
    reviewer_name: 'Pooja Kashyap',
    rating: 5,
    comment: 'Sharma Caterers provided finger-licking food. Guests still praise the live Chaat counter and Gulab Jamuns!',
    event_type: 'Wedding',
    created_at: new Date().toISOString()
  },
  {
    id: 4,
    vendor_id: 8,
    user_id: null,
    reviewer_name: 'Vikram Jha',
    rating: 5,
    comment: 'Utsav Mandap created a mesmerizing floral entrance. Pictures came out stunning.',
    event_type: 'Wedding',
    created_at: new Date().toISOString()
  },
  {
    id: 5,
    vendor_id: 11,
    user_id: null,
    reviewer_name: 'Neha Ranjan',
    rating: 5,
    comment: 'Lens & Moments captured our candid expressions beautifully. The cinematic video had everyone teary-eyed!',
    event_type: 'Wedding',
    created_at: new Date().toISOString()
  },
  {
    id: 6,
    vendor_id: 13,
    user_id: null,
    reviewer_name: 'Deepak Pandey',
    rating: 5,
    comment: 'DJ Akhil kept the Baraat dancing for 3 straight hours. Fantastic sound quality!',
    event_type: 'Sangeet',
    created_at: new Date().toISOString()
  }
];

const initialEvents = [
  {
    id: 1,
    user_id: 1,
    title: 'Rahul & Sneha Wedding Celebration',
    event_type: 'Wedding',
    city: 'Patna',
    event_date: '2026-11-20',
    guest_count: 250,
    total_budget: 300000.00,
    allocated_budget: 260000.00,
    remaining_budget: 40000.00,
    status: 'BOOKED',
    created_at: new Date().toISOString()
  }
];

const initialBookings = [
  {
    id: 1,
    booking_code: 'EH-BK-10021',
    user_id: 1,
    event_id: 1,
    vendor_id: 1,
    event_date: '2026-11-20',
    service_category: 'Venue',
    total_amount: 70000.00,
    advance_percentage: 20.00,
    advance_amount: 14000.00,
    remaining_amount: 56000.00,
    commission_rate: 10.00,
    commission_amount: 7000.00,
    booking_status: 'CONFIRMED',
    payment_status: 'PAID',
    cancellation_reason: null,
    cancelled_by: null,
    cancelled_at: null,
    created_at: new Date().toISOString()
  },
  {
    id: 2,
    booking_code: 'EH-BK-10022',
    user_id: 1,
    event_id: 1,
    vendor_id: 5,
    event_date: '2026-11-20',
    service_category: 'Catering',
    total_amount: 90000.00,
    advance_percentage: 20.00,
    advance_amount: 18000.00,
    remaining_amount: 72000.00,
    commission_rate: 10.00,
    commission_amount: 9000.00,
    booking_status: 'CONFIRMED',
    payment_status: 'PAID',
    cancellation_reason: null,
    cancelled_by: null,
    cancelled_at: null,
    created_at: new Date().toISOString()
  }
];

const initialPayments = [
  {
    id: 1,
    booking_id: 1,
    transaction_ref: 'EH-DEMO-982101',
    amount: 14000.00,
    payment_type: 'ADVANCE',
    payment_method: 'UPI (Simulated)',
    payment_status: 'PAID',
    payment_date: new Date().toISOString(),
    notes: '20% Advance Payment for Venue booking'
  },
  {
    id: 2,
    booking_id: 2,
    transaction_ref: 'EH-DEMO-982102',
    amount: 18000.00,
    payment_type: 'ADVANCE',
    payment_method: 'UPI (Simulated)',
    payment_status: 'PAID',
    payment_date: new Date().toISOString(),
    notes: '20% Advance Payment for Catering booking'
  }
];

const initialRefunds = [];

module.exports = {
  initialUsers,
  initialVendors,
  initialReviews,
  initialEvents,
  initialBookings,
  initialPayments,
  initialRefunds
};
